#define CMAKE_BUILD_GLOG_LOG_LEVEL "INFO"
#define CMAKE_BUILD_DEBUG_INFO_HEAD "SQL"

#define DEBUG_INFO_OPEN  

#ifdef DEBUG_INFO_OPEN
#define DEBUG_INFO(DESCRIBION)\
do{\
    LOG(INFO) << CMAKE_BUILD_DEBUG_INFO_HEAD << ": " << DESCRIBION;\
} while(0)
#else
#define DEBUG_INFO(DESCRIBION)
#endif

#ifdef DEBUG_INFO_OPEN
#define DEBUG_INFO_M(MODULE, DESCRIBION)\
do{\
    LOG(INFO) << CMAKE_BUILD_DEBUG_INFO_HEAD << ": " << MODULE << ": " << DESCRIBION;\
} while(0)
#else
#define DEBUG_INFO_M(MODULE, DESCRIBION)
#endif
